src/views/AdminPanel/PanelsView/Users/Users.js

fix: :ambulance: miss spelled component import in `src/views/AdminPanel` scope

---

src/layouts/WelcomeLayout.js
src/views/Teams/Teams.styles.js
src/views/Teams/WorkspaceView.js
src/views/Teams/items/sides/content/WorkspaceTeamCard/TeamActive.js
src/views/Teams/items/sides/content/WorkspaceUserManagement/WorkspaceUserManagement.js

- feat: :sparkles: implement `ScrollBarProvider` into the `WelcomeLayout`
- style(workspaces): :art: update workspaces view to use the `WelcomeLayout`'s **withScrollbar**
- fix: :lipstick: imrpove `WelcomeLayout` transition effect on route change animation
- feat(workspaces): :sparkles: add ReturnButton element to `WorkspaceUserManagement` view
- fix(workspaces): :bug: additional users count in workspace team cards is not correct
- fix(workspaces): :lipstick: team's user avatars are not correctly stacked

fix(workspace): bugs and minor UI changes

---

.github/workflows/jsdoc-publish.yml
.github/workflows/storybook-publish.yml

fix: :ambulance: workflow's job title not having a `steps` field

---

src/constant/constants.js
src/layouts/Sidebar/items/openSubContents/setting/Setting.js
src/layouts/Sidebar/items/openSubContents/setting/iconList.js
src/layouts/Sidebar/items/openSubContents/setting/items/onboarding/OnboardingContent.js
src/layouts/Sidebar/items/openSubContents/setting/items/onboarding/OnboardingTeamItem.js
src/store/reducers/onboardingReducer.js
src/views/Onboarding/items/content/OnboardingTemplate/OnboardingTemplate.js
src/views/Onboarding/items/content/OnboardingTemplateSelection/OnboardingTemplateSelection.js
src/views/Onboarding/items/content/OnboardingTemplateSetup/OnboardingTemplateSetup.js
src/views/Onboarding/items/others/OnboardingTeamApiCalls.js
src/views/Teams/WorkspaceView.js

- add `ProductTour` component to `Workspace`'s default view
- alter **onboardingReducer**

feat(onboarding): :sparkles: bootstrap sidebar content for onboarding process

---

src/views/Onboarding/items/content/OnboardingTemplateSelection/OnboardingTemplateSelection.styles.js
src/views/Onboarding/items/content/OnboardingTemplateSelection/OnboardingTemplateSelectionCurrentTemplate.js
src/views/Onboarding/items/content/OnboardingTemplateSetup/OnboardingTemplateSetup.js
src/views/Teams/WorkspaceView.js

- change onboarding's finishing url to `Classes` view

fix(onboarding): :lipstick: minor `TemplateSelection` UI syle changes

---

src/layouts/WelcomeLayout.js
src/views/Onboarding/items/content/OnboardingTeam/OnboardingTeam.js
src/views/Onboarding/items/content/OnboardingTeam/OnboardingTeam.styles.js
src/views/Onboarding/items/content/OnboardingUserInfo/OnboardingUserInfo.js

- minor improvements to `WelcomeLayout`

fix(onboarding): :lipstick: `Teams` page final details

---

src/components/Shimmer/Shimmer.js
src/layouts/Sidebar/items/openSubContents/setting/items/onboarding/OnboardingTeamItem.js
src/layouts/WelcomeLayout.js
src/utils/RouteHandler/TransitionSwitchWrapper.js
src/views/Onboarding/items/content/OnboardingTeam/OnboardingTeam.styles.js
src/views/Onboarding/items/content/OnboardingTeam/OnboardingTeamCreationSetWorkFieldContent.js
src/views/Onboarding/items/content/OnboardingTemplateSelection/OnboardingTemplateSelection.js
src/views/Onboarding/items/content/OnboardingTemplateSelection/OnboardingTemplateSelection.styles.js
src/views/Onboarding/items/content/OnboardingTemplateSelection/OnboardingTemplateSelectionGallery.js

- add **darkMode** to `Shimmer` component
- improve transitions between routes

fix(onboarding): :lipstick: improve `TemplateSelection`'s UI to comply with wireframe standards

---

src/components/ImageCropper/AvatarImageCropperItems/AvatarImageCropperTabs.js
src/components/TabView/useTabView.js
src/views/Templates/TemplateSinglePage/items/TemplateGeneralSetting/CMConfidetialitySetting/SelectObject/SelectObjectDropDown.js
src/views/Templates/TemplateSinglePage/items/TemplateGeneralSetting/items/TemplateUploadIcon.js

fix: :ambulance: change `TabView`'s **Item** and **Action** child detection

---

src/components/ImageCropper/AvatarImageCropperItems/AvatarImageCropperTabs.js

fix: :adhesive_bandage: image dimentions state not updating in `AvatarImageCropper` component

---

src/views/Onboarding/items/content/OnboardingTemplateSelection/OnboardingTemplateSelectionNode.js

fix(onboarding): :ambulance: render error in `OnbordingTemplateSelection`

---

.eslintrc.js
src/apiHelper/ApiHandlers/apiCallHelpers.ts
src/components/BlockEditor/API.ts
src/components/BlockEditor/Block.tsx
src/components/BlockEditor/BlockEditor.tsx
src/components/BlockEditor/BlockEditor.type.ts
src/components/BlockEditor/data.ts
src/components/BlockEditor/plugins.ts
src/components/BlockEditor/useAutoSave.ts
src/views/Node/nodeDetails/NodeDetails.js
src/views/Node/nodeDetails/items/Collector.js

- fix prettier configuration
- configure **no-unused-vars** rule in eslint to ignore variables stating with `_`

feat(node-pages): :construction: implement `BlockEditor` component as node page element

---

package.json
src/components/CustomTable/CustomTable.js
src/components/CustomTable/CustomTable.styles.js
src/components/CustomTable/MyTable/Mytable.js
src/constant/CssVariables.js
src/views/Onboarding/items/content/OnboardingTemplateSelection/OnboardingTemplateSelection.styles.tsx
src/views/Teams/items/others/table/ResponsiveTable.js
yarn.lock

- update `TCV_VERY_TRANSPARENT` constant with proper css variable name
- implemenet `@cliqmind/react-table` imports

feat: :heavy_plus_sign: replace `react-table` package with `@cliqmind/react-table` temporarily

---

src/components/BlockEditor/BlockEditor.tsx
src/components/FormElements/FormFill/FormFill.js
src/components/FormElements/FormFill/types/ParagraphField/ParagraphField.tsx
src/components/FormElements/FormFill/types/prepareForm.js
src/views/Node/nodeDetails/items/Collector.js
src/views/Node/nodeDetails/items/WikiBlock.tsx

- seperate `BlockEditor` and `WikiBlock` components

feat(node-pages): :sparkles: implement `ParagraphField` as form element

---

src/components/BlockEditor/BlockEditor.tsx
src/components/FormElements/FormFill/types/ParagraphField/ParagraphField.tsx
src/components/FormElements/FormFill/types/binary/BinaryField.js
src/components/FormElements/FormFill/types/date/DateField.js
src/components/FormElements/FormFill/types/multiSelect/MultiSelectField.js
src/components/FormElements/FormFill/types/singleSelect/SingleSelectField.js
src/components/FormElements/FormFill/types/textField/TextField.js
src/components/Icons/TagIcon/TagIcon.js
src/layouts/WelcomeLayout.js
src/views/Node/nodeDetails/NodeDetails.js
src/views/Node/nodeDetails/NodeDetails.style.js
src/views/Node/nodeDetails/items/Collector.js
src/views/Node/nodeDetails/items/MainNode.js
src/views/Node/nodeDetails/items/topBar/Creators.js

- add `TagIcon` component
- implement focus/blur effect for editing node elements

fix(node-pages): :construction: improve UI/UX of node elements

---

src/components/FormElements/FormFill/types/singleSelect/SingleSelectField.js

fix(node-pages): :ambulance: `SingleSelectField` throwing an error in production build

---

src/components/BlockEditor/BlockEditor.tsx
src/components/FormElements/FormFill/types/ParagraphField/ParagraphField.tsx
src/components/FormElements/FormFill/types/binary/BinaryField.js
src/components/FormElements/FormFill/types/date/DateField.js
src/components/FormElements/FormFill/types/file/FileField.js
src/components/FormElements/FormFill/types/file/FileShowCell.js
src/components/FormElements/FormFill/types/multiLevel/MultiLevelField.js
src/components/FormElements/FormFill/types/multiSelect/MultiSelectField.js
src/components/FormElements/FormFill/types/singleSelect/SingleSelectField.js
src/components/FormElements/FormFill/types/textField/TextField.js
src/views/Node/nodeDetails/items/MainNode.js
src/views/Node/nodeDetails/items/WikiBlock.tsx

- improve empty field UI styles

fix(node-pages): :bug: `MultiLevelField` not working as expected

---

src/components/BlockEditor/BlockEditor.tsx
src/components/FormElements/FormFill/types/textField/TextField.js
src/components/UserManagement/UserGroupSelect/UserGroupSelect.tsx
src/components/UserManagement/UserGroupSelect/UserGroupSelectStyles.ts
src/components/UserManagement/UserGroupSelect/items/UserSelect.tsx
src/views/Node/nodeDetails/items/topBar/Creators.js
src/views/Node/nodeDetails/items/topBar/EditContributersModal.js
src/views/Node/nodeDetails/items/topBar/TopBar.style.tsx

- imrpove `FormFill`'s paragraph and text placeholder conditions

fix(node-pages): :ambulance: UI issues with `UserGroupSelect` component

---

src/components/BlockEditor/BlockEditor.tsx
src/components/BlockEditor/blockEditorCodeBlockTheme.module.css
src/components/BlockEditor/plugins.ts

style(node-pages): :lipstick: change `BlockEditor` code block UI style

---

src/App.js
src/components/FormElements/ElementTypes/Select/SelectInputField.tsx
src/components/FormElements/ElementTypes/multiLevel/MultiLevelField.tsx
src/components/Modal/Modal.js
src/components/ScrollBarProvider/ScrollBarProvider.js
src/components/UserManagement/UserGroupSelect/UserGroupSelect.tsx
src/views/Node/nodeDetails/NodeDetails.style.js
src/views/Node/nodeDetails/items/Collector.js
src/views/Node/nodeDetails/items/sideColumn/LogItem.js
src/views/Node/nodeDetails/items/sideColumn/SideColumn.js
src/views/Node/nodeDetails/items/sideColumn/SideHistoryLog.js
src/views/Node/nodeDetails/items/sideColumn/TimeLineItem.js
src/views/Node/nodeDetails/items/topBar/EditContributersModal.js
src/views/Node/nodeDetails/items/topBar/TopBar.style.tsx
src/views/Node/nodeDetails/items/topBar/TopBar.tsx

fix(node-page): :children_crossing: enhance node page UI/UX effects

---

src/components/CustomTable/TableAction.js
src/components/FormElements/FormFill/types/form/Table.js

fix(node-page): :bug: table form's new row not working as expected

---

src/components/CustomTable/cellTypes/action/ActionsCell.js
src/components/CustomTable/cellTypes/text/TextCell.js
src/components/FormElements/ElementTypes/Select/SelectInputField.tsx
src/components/FormElements/ElementTypes/multiLevel/MultiLevelField.tsx
src/components/Icons/DragIcon/Drag.js
src/views/Node/nodeDetails/items/MainNode.js
src/views/Node/nodeDetails/items/sideColumn/SideHeader.js

fix(node-page): :ambulance: minor UX improvments for table form elements

---

src/components/AdvancedSearch/AdvancedSearchDesktop.js
src/components/BlockEditor/BlockEditor.tsx
src/components/CustomTable/CustomTable.js
src/components/CustomTable/TableAction.js
src/components/FormElements/ElementTypes/Select/SelectInputField.tsx
src/components/FormElements/ElementTypes/multiLevel/MultiLevelField.tsx
src/components/FormElements/FormFill/types/file/FileField.js
src/components/FormElements/FormFill/types/form/Table.js
src/components/FormElements/FormFill/types/keywordField/KeywordField.tsx
src/components/FormElements/FormFill/types/textField/TextField.js
src/components/Inputs/Input.js
src/components/RelatedTopicsTab/RelatedTopicsTab.tsx
src/components/ScrollBarProvider/ScrollBarProvider.js
src/views/Templates/TemplateSinglePage/items/TemplateGeneralSetting/CMConfidetialitySetting/CMConfidentialitySettingStyle.js
src/views/Templates/settings-view/items/TemplateCreateNew.js

- class items container wont respond ro scrol
- add number/text lengths to `TextField` component

fix(node-page): :ambulance: node page elements not working as expected

---

src/components/FormElements/FormFill/types/textField/TextField.js
src/helpers/helpers.ts

feat(node-page): :bug: replace native js solution of thousands separator for`TextInput`

---

src/components/FormElements/ElementTypes/Select/SelectInputField.tsx
src/components/FormElements/ElementTypes/multiLevel/MultiLevelField.tsx
src/components/FormElements/FormFill/types/textField/TextField.js
src/views/Node/nodeDetails/items/topBar/NodePageRelatedNodeItems.tsx
src/views/Onboarding/items/content/OnboardingTemplateSelection/OnboardingTemplateSelectionNode.js
src/views/Templates/TemplateSinglePage/items/TemplateFormSettings/TemplateFormWrapper.js

implement node preview for template form builder

fix(template-management): :ambulance: `MultiLevelField` not working as expected

---

src/apiHelper/ApiHandlers/CNAPI/api-templates.ts
src/components/Carousel/Carousel.styles.js
src/components/FormElements/ElementTypes/Select/SelectInputField.tsx
src/components/FormElements/ElementTypes/multiLevel/MultiLevelField.tsx
src/components/TemplatesGallery/TemplatesGallery.js
src/views/Onboarding/items/content/OnboardingTemplateSelection/OnboardingTemplateSelection.js
src/views/Onboarding/items/content/OnboardingTemplateSelection/OnboardingTemplateSelection.styles.tsx
src/views/Onboarding/items/content/OnboardingTemplateSelection/OnboardingTemplateSelectionCarousel.js
src/views/Templates/settings-view/TemplatesSettings.js
src/views/Templates/settings-view/items/TemplateCreateNew.js

patched minor UI/UX styles and functionality bugs

---

package.json
src/layouts/NewSidebar/MainSidebar.tsx
src/layouts/NewSidebar/sidebarContents/sidebarContentsClasses.tsx
src/layouts/NewSidebar/sidebarContents/sidebarContentsDefault.ts
src/layouts/NewSidebar/sidebarContents/sidebarContentsNodePage.ts
src/layouts/NewSidebar/sidebarContents/sidebarContentsProfile.ts
src/layouts/NewSidebar/sidebarContents/sidebarContentsworkspaces.ts
yarn.lock

- improve sidebar navigation indicator
- fix scroll bar effects

feat: :arrow_up: upgrade `rv-components` package

---

src/components/Breadcrumb/Breadcrumb.js
src/layouts/NewSidebar/MainSidebar.tsx
src/layouts/NewSidebar/sidebarContents/sidebarContentsClasses.tsx
src/layouts/NewSidebar/sidebarContents/sidebarContentsDefault.ts
src/layouts/NewSidebar/sidebarContents/sidebarUserAvatar.tsx
src/layouts/NewSidebar/sidebarContents/useSidebarContent.tsx
src/layouts/NewSidebar/sidebarStyles.module.scss
src/views/Classes/Classes.js
src/views/Teams/items/sides/welcome/WorkspaceWelcome.js
src/views/Templates/settings-view/TemplatesSettings.js

feat: :bug: mainSidebar content changes according to user Level

---

package.json
src/components/AdvancedSearch/AdvancedSearch.style.js
src/components/AdvancedSearch/AdvancedSearchDesktop.js
src/components/AdvancedSearch/items/FilterBar/FilterBar.js
src/components/Buttons/Button.tsx
src/layouts/NewSidebar/MainSidebar.tsx
src/layouts/NewSidebar/sidebarContents/sidebarContentsClasses.tsx
src/layouts/NewSidebar/sidebarContents/sidebarContentsEmptyAction.tsx
src/layouts/NewSidebar/sidebarContents/sidebarContentsProfile.tsx
src/layouts/NewSidebar/sidebarContents/sidebarContentsTeamSettings.tsx
src/layouts/NewSidebar/sidebarContents/sidebarContentsworkspaces.ts
src/layouts/NewSidebar/sidebarContents/useSidebarContent.tsx
src/views/Profile/Profile.styles.js
src/views/Profile/items/customization/Profile-Customization.js
src/views/Profile/items/security/Profile-Security.js
yarn.lock

- update `@cliqmind/rv-components` dependencies

fix(redesign): :bug: remove depending box-sizing to `content-box`
